apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whatshouldido-ingress
  namespace: whatshouldido
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: api.whatshouldido.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whatshouldido-svc
            port:
              number: 80
