apiVersion: v1
kind: Secret
metadata:
  name: whatshouldido-secrets
  namespace: whatshouldido
type: Opaque
stringData:
  ConnectionStrings__Default: "Host=<rds-endpoint>;Database=<db-name>;Username=<db-user>;Password=<db-pass>;"
