apiVersion: v1
kind: Service
metadata:
  name: whatshouldido-svc
  namespace: whatshouldido
spec:
  type: LoadBalancer
  selector:
    app: whatshouldido-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
