services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "1471027Demo"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: /src/WhatShouldIDo.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=WhatShouldIDo;User Id=sa;Password=1471027Demo;TrustServerCertificate=True;Encrypt=False"
      Redis__ConnectionString: "redis:6379"
      GooglePlaces__ApiKey: "REMOVED"REMOVED_GOOGLE_PLACES_KEY"
      OpenTripMap__ApiKey: "REMOVED"REMOVED_OPENTRIPMAP_KEY"
      OpenWeather__ApiKey: "your_openweather_api_key_here"
      Geoapify__ApiKey: "your_geoapify_api_key_here"
    depends_on:
      - sqlserver
      - redis 
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  sqlserverdata:
